### ISSUE TITLE
不知有空从例程中整理一些短文发到专栏吗?

### ISSUE THREAD

**Issue by nobodxbodon** [cflw/cflw_py#1]
因为看到[最近的投稿](https://zhuanlan.zhihu.com/p/51097325), 想到你之前积累的这些例程.

**Comment by cflw** [comment]
没问题。周末我会试着写篇文章投投看。

**Comment by nobodxbodon** [comment]
期待~ 你的[经验心得](https://github.com/program-in-chinese/overview/issues/45#issuecomment-431040640)也是很合适的素材.

**Comment by nobodxbodon** [comment]
可否在首页添加知乎文章的链接? 因为是比首页更详细的介绍文档. 像我的[这个](https://github.com/program-in-chinese/quan3)
